### ISSUE TITLE
Simpler, smaller configuration file.

### ISSUE THREAD

**Issue by juhacz** [Temporalitas/ipv6-proxy-server#1]
It seems to me that it is possible to simplify the script and, above all, the configuration file by following these changes in 3proxy. https://github.com/3proxy/3proxy/issues/639 .

Grettings

**Comment by Theodikes** [comment]
Sorry, cannot do this, because script have to add each specific ipv6 address to interface via command `ip -6 addr add $ipv6_address dev $interface_name`. If you leave the generation of random addresses on 3proxy, it's not very clear how to assing them to interface.
I tried using [ndppd](https://github.com/DanielAdolfsson/ndppd), but it wont working on some servers. 
If you have any ideas for an alternative to ndppd, be sure to write here

**Comment by juhacz** [comment]
I'm not a Linux expert, I only know the basics, but some time ago I needed to be able to change the ipv6 address on every request in curl on my VPS, for which I had a whole ipv6 class at my disposal. On Debian 12 I did it by setting up like this (VPS in Alwyzon):

```
auto lo
iface lo inet loopback
    dns-nameservers 46.102.157.42 46.102.157.27 2a0d:f302:99::99
    dns-search vie.alwyzon.net

iface lo inet6 loopback
	address 2a0d:f302:xxx:xxxx::/64
	post-up ip route add local 2a0d:f302:xxx:xxxx::/64 dev lo
	pre-down ip route del local 2a0d:f302:xxx:xxxx::/64 dev lo

auto eth0
iface eth0 inet static
    address 86.106.xxx.xx/26
    gateway 86.106.182.65

iface eth0 inet6 static
	address 2a0d:f302:xxx:xxxx::1/64	
	gateway 2a0d:f302:xxx::1
```
Maybe this will help you solve the problem.
Regards

**Comment by Theodikes** [comment]
> iface lo inet6 loopback

This wont working on servers with automatically configuring network interfaces on web panel, like Vultr. Requires everything to work without changing `/etc/network/interfaces`

**Comment by doim** [comment]
> It seems to me that it is possible to simplify the script and, above all, the configuration file by following these changes in 3proxy. [3proxy/3proxy#639](https://github.com/3proxy/3proxy/issues/639) .
> 
> Grettings

#  every request ,alway same ipv6 of last added to eth0
~# curl -x usryourname:pass065@209.141.55.82:3128 icanhazip.com
### 2605:6400:48:f897:8d29:a4d4:9496:923b
~# curl -x usryourname:pass065@209.141.55.82:3128 icanhazip.com
### 2605:6400:48:f897:8d29:a4d4:9496:923b

# config is 
----------
auth none
flush
allow * * ::/0
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128

# ifconfig eth0 
------
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 209.141.55.82 netmask 255.255.255.0 broadcast 209.141.55.255
inet6 2605:6400:48:886f:ff7:b366:fd3f:160a prefixlen 48 scopeid 0x0
inet6 2605:6400:48:f897:8d29:a4d4:9496:923b prefixlen 48 scopeid 0x0
inet6 2605:6400:20:e5:fa82:ae0b:5e66:d632 prefixlen 48 scopeid 0x0
inet6 fe80::216:17ff:fe61:1536 prefixlen 64 scopeid 0x20
ether 00:16:17:61:15:36 txqueuelen 1000 (Ethernet)
RX packets 6056 bytes 526420 (526.4 KB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 4493 bytes 707453 (707.4 KB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

## what' wrong about me ?

**Comment by doim** [comment]
> 

how to set ipv6 to ethernet?

3proxy.cfg use ,it willl get 502 because 3proxy random ipv6 have not set to ethernet device.

allow * * ::/0
parent 1000 xxx:xxx:xxx:xxx:/64 0


3proxy.log get 00013 code 

and return 
502 Bad Gateway,Host Not Found or connection failed

**Comment by doim** [comment]
> > iface lo inet6 loopback
> 
> This wont working on servers with automatically configuring network interfaces on web panel, like Vultr. Requires everything to work without changing `/etc/network/interfaces`

3proxy author [z3APA3A](https://github.com/z3APA3A) have supply this funcation and tip user to used it.

**Comment by testkings123** [comment]
What is the reason for this error, friends? Vultr

Error: /etc/network/interfaces has no inet6 (IPv6) configuration.

**Comment by Temporalitas** [comment]
> What is the reason for this error, friends? Vultr
> 
> Error: /etc/network/interfaces has no inet6 (IPv6) configuration.

![image](https://github.com/user-attachments/assets/16a6ae34-d3c2-4135-8389-f93124b78f74)
