### ISSUE TITLE
what company do you recommend for ipv6 vps/vds 

### ISSUE THREAD

**Issue by barutlift** [Temporalitas/ipv6-proxy-server#30]
hi, im new user for proxy server i searched all of week but i confused so what company and plan do you reccomended for ipv6 vps/vds. i need to use 8 ipv6 proxies simultaneouslyper for 7 minutes. 200 proxies for daily
thanks for answers

**Comment by Temporalitas** [comment]
> hi, im new user for proxy server i searched all of week but i confused so what company and plan do you reccomended for ipv6 vps/vds. i need to use 8 ipv6 proxies simultaneouslyper for 7 minutes. 200 proxies for daily thanks for answers

Vultr or Aeza.
