### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by DarkReapa** [Temporalitas/ipv6-proxy-server#8]
Hi, can you add IPv6 rotation functionality by curl request? For example, like here https://blog.vpsville.ru/blog/howto/243.html

**Comment by Theodikes** [comment]
This wont work. If you know, how to create access from any random subnet address without adding it directly via `ip - addr add ...`, write here please

**Comment by DarkReapa** [comment]
ip -6 route add local PREFIX/64 dev lo 
Setting up ndppd
apt install ndppd
/etc/ndppd.conf

`route-ttl 30000
proxy eth0 {
   router no
   timeout 500   
   ttl 30000
   rule PREFIX/64 {
      static
   }
}`

In this case, you do not need to add each address in the interface

**Comment by Theodikes** [comment]
> ip -6 route add local PREFIX/64 dev lo 
> Setting up ndppd
> apt install ndppd
> /etc/ndppd.conf
> 
> route-ttl 30000
> proxy eth0 {
>    router no
>    timeout 500   
>    ttl 30000
>    rule PREFIX/64 {
>       static
>    }
> }
> 
> service ndppd start
> service ndppd restart
> In this case, you do not need to add each address in the interface

https://github.com/Theodikes/ipv6-proxy-server/issues/1#issuecomment-1484216338

ndppd not working on many servers. Write please in Telegram (reame), if you can make ndppd working on server that I'll provide, it will be good
